import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

export const generateMentorReport = async (data) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const chunks = [];

            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));

            // Header
            doc
                .fillColor('#444444')
                .fontSize(20)
                .text('MentorLink - Performance Insights', { align: 'center' });
            doc.moveDown();

            // Mentor Info
            doc
                .fontSize(14)
                .fillColor('#333333')
                .text(`Mentor: ${data.mentorName}`)
                .text(`Report Period: ${data.period}`)
                .text(`Generated on: ${new Date().toLocaleDateString()}`);
            doc.moveDown();

            // Statistics Summary
            doc
                .fontSize(16)
                .fillColor('#2c3e50')
                .text('Performance Summary', { underline: true });
            doc.moveDown(0.5);

            const stats = [
                ['Total Earnings', `$${data.totalEarnings || 0}`],
                ['Total Sessions', `${data.totalSessions || 0}`],
                ['Average Rating', `${data.averageRating || 0}/5`],
                ['Completion Rate', `${data.completionRate || 0}%`],
                ['Student Retention', `${data.retentionRate || 0}%`]
            ];

            stats.forEach(([label, value]) => {
                doc
                    .fontSize(12)
                    .fillColor('#444444')
                    .text(`${label}: `, { continued: true })
                    .fillColor('#000000')
                    .text(value);
            });
            doc.moveDown();

            // Recent Sessions Table Header
            if (data.recentSessions && data.recentSessions.length > 0) {
                doc
                    .fontSize(16)
                    .fillColor('#2c3e50')
                    .text('Recent Sessions', { underline: true });
                doc.moveDown(0.5);

                // Simple table logic
                let y = doc.y;
                doc.fontSize(10).fillColor('#333333');
                doc.text('Date', 50, y);
                doc.text('Student', 150, y);
                doc.text('Topic', 300, y);
                doc.text('Amount', 450, y);

                doc.moveTo(50, y + 15).lineTo(550, y + 15).stroke();
                y += 20;

                data.recentSessions.forEach(session => {
                    doc.text(new Date(session.sessionDate).toLocaleDateString(), 50, y);
                    doc.text(session.student?.name || 'N/A', 150, y);
                    doc.text(session.topic || 'Mentoring', 300, y);
                    doc.text(`$${session.amount || 0}`, 450, y);
                    y += 20;

                    if (y > 700) {
                        doc.addPage();
                        y = 50;
                    }
                });
            }

            // Footer
            const pageCount = doc.bufferedPageCount;
            for (let i = 0; i < pageCount; i++) {
                doc.switchToPage(i);
                doc
                    .fontSize(8)
                    .fillColor('#999999')
                    .text(
                        'Generated by MentorLink Analytics Engine',
                        50,
                        doc.page.height - 50,
                        { align: 'center' }
                    );
            }

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
};
